name: cpc37
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pytorch
  - torchvision
  - cudatoolkit=11.1
  - psutil
  - pip
  - openblas-devel
  - tqdm
  - nose
  - cython
  - pysoundfile
  - pip:
    - progressbar2
    - matplotlib
    - torchaudio
